# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='measurement (optional)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='preparation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='preparation (optional)'),
        ),
    ]
